services:  
  db:
    image: postgis/postgis:17-3.5
    container_name: ucp_db
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
       POSTGRES_DB: postgres
    volumes:
        - db_data:/var/lib/postgresql/data
  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    image: adminer:4.17.1
    depends_on: 
      - db
    ports:
      - 8080:8080
    container_name: ucp_adminer
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:7777
    volumes:
      - .:/src
    ports:
      - 7777:7777
    depends_on:
      - db
    container_name: ucp_web

networks:
  ucp_default:
    driver: bridge

volumes:
  db_data:
